# Generated by Django 5.2.3 on 2025-06-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(help_text='Loyalty member or user ID (e.g. CoffeeChain Member ID)', max_length=100)),
                ('origin', models.CharField(help_text='IATA origin airport code (e.g. CPT)', max_length=3)),
                ('destination', models.CharField(help_text='IATA destination airport code (e.g. JNB)', max_length=3)),
                ('departure_date', models.DateField(help_text='Outbound departure date')),
                ('return_date', models.DateField(blank=True, help_text='Return date (if round trip). Leave blank for one-way.', null=True)),
                ('cabin_class', models.CharField(help_text='Cabin class (e.g. economy, business)', max_length=20)),
                ('num_passengers', models.PositiveIntegerField(default=1, help_text='Number of passengers')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Loyalty amount spent (e.g. 1200 points)', max_digits=12)),
                ('loyalty_currency', models.CharField(help_text='The loyalty currency used (e.g. Stars, Points, Coins)', max_length=20)),
                ('airline', models.CharField(blank=True, help_text='Airline code (e.g. BA, LH)', max_length=10, null=True)),
                ('flight_number', models.CharField(blank=True, help_text='Flight number assigned by airline', max_length=20, null=True)),
                ('reference', models.CharField(blank=True, help_text='External reference ID from provider (e.g. Duffel booking ID)', max_length=100, null=True)),
                ('raw_response', models.JSONField(blank=True, help_text='Raw API response for auditing/troubleshooting', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the booking', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp when the booking was cancelled', null=True)),
                ('refund_status', models.CharField(blank=True, help_text='Status of refund processing (e.g. processed, pending, failed)', max_length=20, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded to loyalty account', max_digits=12, null=True)),
                ('refund_processed_at', models.DateTimeField(blank=True, help_text='Timestamp when refund was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Owning tenant for this booking (e.g. CoffeeChain)', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
