# Generated by Django 5.2.3 on 2025-06-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name of the tenant, e.g. 'CoffeeChain'", max_length=100)),
                ('slug', models.SlugField(help_text="Unique identifier used in headers and URL routing, e.g. 'coffeechain'", unique=True)),
                ('auth_method', models.CharField(choices=[('api_key', 'API Key'), ('oauth2', 'OAuth 2.0'), ('jwt', 'JWT')], help_text="Authentication mechanism used by the tenant's API", max_length=20)),
                ('base_url', models.URLField(help_text="Base URL of the tenant's loyalty program API")),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=100, help_text='Maximum number of allowed requests per minute for this tenant')),
                ('config', models.JSONField(default=dict, help_text='Flexible per-tenant configuration (e.g., currency, ID headers, special rules)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
